import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Provider from './provider'
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ['latin']})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //clerkProvider make user login/auth info available to any component inside.
    <ClerkProvider>
    <html lang="en">
      <body
      >
        {/* {children} = all pages/components of your app.

        <Provider> gives them access to your app’s state (theme, settings, global data, etc.) */}
        <Provider>
        {children}
        <Toaster/>
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
